version: '3.8'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - flask

  flask:
    build: ./Flask
    container_name: flask
    ports:
      - "5001:5000"
    depends_on:
      - dbmaria

  dbmaria:
    image: mariadb:10.5
    container_name: dbmaria
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quizdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dbmaria/quizdb_backup.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
